### PR TITLE
Split into smaller travis tests

### PR DESCRIPTION
**Pull request by zachzzc**

### CODE REVIEW

**Comment by msfschaffner** [comment]
Can you try to increase the timeout for the tests that fail?

https://docs.travis-ci.com/user/common-build-problems/

**Comment by zachzzc** [comment]
It seems like the 25min wait time is not still enough. I will further increase it to 60min

**Comment by msfschaffner** [comment]
So for some reason torture gets stuck with the writeback cache. This cache has a couple of issues anyway, and we currently do not consider it as `production ready`. Hence I would say we disable the torture test for the writeback cache, and only run it on the write-through cache (there it actually completes after 10mins or so).

**Comment by zachzzc** [comment]
Torture test is unstable for both WT and WB cache. I don’t known if we want to disable both of them.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by msfschaffner** [comment]
For the sake of productivity, let's disable them for the time being. I've opened an issue to track this, since we should track down what the problems are.

**Comment by msfschaffner** [comment]
Thanks!

**Pull request merged**
