### PR TITLE
Improve Tandem Simulation, switch-able caches and fix a cache-bug

### PR DESCRIPTION
**Pull request by zarubaf**

### CODE REVIEW

**Comment by zarubaf** [comment]
Yeah, its all commented out stuff at the moment. Not sure, I can remove it from the repository if you think that would be better.

**Comment by msfschaffner** [comment]
Let's not clutter the repo if we are not going to use it...

**Comment by zarubaf** [comment]
Done

**Comment by zarubaf** [comment]
Ping @stmach @msfschaffner

**Comment by msfschaffner** [comment]
Ok to move forward from my side.

**Comment by zarubaf** [comment]
Can you accept sign the review then pls?

**Comment by stmach** [comment]
LGTM

**Pull request merged**
