### PR TITLE
Misc fixes (Verilator compliance, PK simulation issues, PLIC regmap, updated DM)

### LINKED ISSUE #211: Variane_testharness seems to get stuck
Hi,

I'm new to the riscv tool chain and Ariane. I have installed the tools from [https://github.com/riscv/riscv-tools](url)  and downloaded the master branch of Ariane, following the getting started guide. I managed to install everything, but when I try to execute Variane_testharness with pk and a simple hello world example, the program never ends. I run the same command as in the guide:

`work-ver/Variane_testharness $RISCV/riscv64-unknown-elf/bin/pk hello.elf
`

But what I see in the trace is that it seems to get stuck with the following instruction:

`1368128 0x8000255a M (0x0000a001) c.j     pc + 0
`

Do you know a possible cause for this problem? Is this normal? I run the program for more than 10 minutes and I don't think it should take that long. Running the same elf file with Spike finishes correctly.

Thanks!

### PR DESCRIPTION
**Pull request by msfschaffner**

### CODE REVIEW

**Comment by msfschaffner** [comment]
This is good to go once we've checked the standalone FPGA build. The OpenPiton build and CI works as well.

**Comment by zarubaf** [comment]
Cool, thanks. I will give it a spin and merge afterwards.

**Comment by zarubaf** [comment]
Okay, status is that it breaks the single-core case. It seems that there is something off with the `PLIC` as it hangs after it switches on the `tty` driver.

**Comment by msfschaffner** [comment]
This version bump fixes the address of the interrupt pending register.

**Comment by msfschaffner** [comment]
This reverts back to the generated plic regfile, since the SV version did not properly work. The `rv_plic` repo now also contains the regmap generator script.

**Comment by zarubaf** [comment]
Thanks, the stuff is merged. I've kept this branch untouched as `openpiton-dev` is pointing twoards it. Feel free to close this PR whenever you've changed the refs accordingly.

**Pull request closed without merging**
