### PR TITLE
Remove interface name aliasing to keep VCS happy

### PR DESCRIPTION
**Pull request by jrrk**
At the moment in an alias for Slave and out an alias for Master. This causes VCS to complain and refuse to compile when the names are mixed. This PR remove the in and out aliases. Requires [this PR](https://github.com/pulp-platform/axi/pull/9)

### CODE REVIEW

**Comment by zarubaf** [comment]
Okay I am okay with this. Lets wait for the depending PR before we proceed.

**Comment by zarubaf** [comment]
@jrrk The PR is merged, can you please update here so that CI passes and we can merge?

**Comment by jrrk** [comment]
It seems like quite a lot has changed in the meantime, I have rebased manually as best I can, but which may or may not be correct. Perhaps somebody who knows GitHub better than me can cherry-pick the stuff that matters, if necessary.

**Comment by jrrk** [comment]
I've completed everything I can think of, the Travis is still failing due to a timeout. Perhaps this should be manually reviewed to approve for merge because I see no reason why it would affect simulation performance.

**Comment by msfschaffner** [comment]
Hi Jonathan, you might want to pull in #248 . We split up the Travis targets and disabled Torture for the time being to work around the timeout issue. In the long run we should rework the tests, e.g. bundle some of the redundant compilation stages, and switch to a different loading mechanism than via the FESVR (this is unfortunately quite wasteful in terms of simulation cycles).

**Comment by zarubaf** [comment]
Closing in favor of #254

**Pull request closed without merging**
